// <auto-generated />
using System;
using Drps.Ingestion.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drps.Ingestion.Persistence.Migrations
{
    [DbContext(typeof(DrpsDbContext))]
    [Migration("20260801003634_AddAmbiguousFireSkip")]
    partial class AddAmbiguousFireSkip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drps.Shared.Models.AdjusterAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdjusterParameterVersion")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AllocationDollarAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AllocationPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("AsOfTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("GateScoreId")
                        .HasColumnType("bigint");

                    b.Property<bool>("InsiderDataUnverified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("InsiderMultiplierApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1.0m);

                    b.Property<decimal>("OptionsFlowMultiplierApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1.0m);

                    b.Property<bool>("ShareCapDeficient")
                        .HasColumnType("bit");

                    b.Property<decimal>("ShareCount")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("GateScoreId");

                    b.ToTable("AdjusterAllocations");
                });

            modelBuilder.Entity("Drps.Shared.Models.AdjusterParameters", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseReservePercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxConcurrentPositions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<decimal>("ReserveMilestoneOne")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReserveMilestoneTwo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReserveStepPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SectorCapPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TierOneBaseRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TierOneCeiling")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TierOneFloor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TierThreeBaseRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TierTwoBaseRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TierTwoCeiling")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("AdjusterParameters");
                });

            modelBuilder.Entity("Drps.Shared.Models.AmbiguousFireSkip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "ConsumedAt");

                    b.ToTable("AmbiguousFireSkips");
                });

            modelBuilder.Entity("Drps.Shared.Models.BarVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ComputationVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchedSourceCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrimarySourceValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SourceCount")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ToleranceApplied")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp", "Resolution");

                    b.ToTable("BarVerifications");
                });

            modelBuilder.Entity("Drps.Shared.Models.ConsecutiveLossCircuitBreaker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ConsecutiveLossCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("LastEvaluatedPositionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ResetAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Tripped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("TrippedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ConsecutiveLossCircuitBreakers");
                });

            modelBuilder.Entity("Drps.Shared.Models.Discrepancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FieldOrBarType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PercentDiff")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ResolutionMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Unresolved");

                    b.Property<int>("SourceA")
                        .HasColumnType("int");

                    b.Property<int>("SourceB")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ValueA")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("ValueB")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.ToTable("Discrepancies");
                });

            modelBuilder.Entity("Drps.Shared.Models.ExcludedTicker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("ExcludedTickers");
                });

            modelBuilder.Entity("Drps.Shared.Models.FieldVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ComputationVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MatchedSourceCount")
                        .HasColumnType("int");

                    b.Property<int>("SourceCount")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ToleranceApplied")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "FieldName", "Timestamp");

                    b.ToTable("FieldVerifications");
                });

            modelBuilder.Entity("Drps.Shared.Models.GateParameters", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BuyThreshold")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExitThreshold")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NoBuySessionCount")
                        .HasColumnType("int");

                    b.Property<decimal>("RsiCompositeWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RsiFloorQuality")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RsiLowerBound")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RsiPeak")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RsiUpperBound")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RvolCeilingMultiple")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RvolFloorMultiple")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RvolFullWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RvolHalfWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WatchThreshold")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("GateParameters");
                });

            modelBuilder.Entity("Drps.Shared.Models.GateScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AtrCleanPreEventValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AtrValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("CompositeScore")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("DataAsOfDate")
                        .HasColumnType("date");

                    b.Property<bool>("EarningsDataUnverified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("GateParameterVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasTiingoCorrectedData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasUnverifiedPartialCreditData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDmaAligned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDmaVerifiedAsync_Result")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEarningsBlackoutActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStaleData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NoBuyListExpiration")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RsiQuality")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RsiValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RvolQuality")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RvolValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ScoredThroughExDividendEvent")
                        .HasColumnType("bit");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("VerificationScopeLimited")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GateParameterVersion");

                    b.ToTable("GateScores");
                });

            modelBuilder.Entity("Drps.Shared.Models.KillSwitchCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OpenAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TradingDate");

                    b.ToTable("KillSwitchCounters");
                });

            modelBuilder.Entity("Drps.Shared.Models.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdjusterAllocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CloseOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CoolDownStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EntryAtr")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EntryQuantity")
                        .HasColumnType("decimal(18,9)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ExitQuantity")
                        .HasColumnType("decimal(18,9)");

                    b.Property<string>("ExitReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GateScoreId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("HighWaterMark")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("LowGradeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpenOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlateauBaselineDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PlateauBaselinePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PlateauDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReactivatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("TpProgressAtExit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TpTargetPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AdjusterAllocationId");

                    b.HasIndex("GateScoreId");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasFilter("[ExitDate] IS NULL");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Drps.Shared.Models.PositionReconciliationDiscrepancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AlpacaAverageEntryPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AlpacaQuantity")
                        .HasColumnType("decimal(18,9)");

                    b.Property<DateTime>("DetectedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LedgerPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LedgerQuantity")
                        .HasColumnType("decimal(18,9)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("PositionReconciliationDiscrepancies");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawEarningsObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NextEarningsDate")
                        .HasColumnType("date");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Source", "FetchedAt");

                    b.ToTable("RawEarningsObservations");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawExDividendObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ExDividendDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("VariancePct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "ExDividendDate", "Source");

                    b.ToTable("RawExDividendObservations");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawFieldObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawValueText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "FieldName", "Timestamp");

                    b.ToTable("RawFieldObservations");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawInsiderObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DollarValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsiderName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Source", "TransactionDate");

                    b.ToTable("RawInsiderObservations");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawOhlcvBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp", "Resolution");

                    b.ToTable("RawOhlcvBars");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawRegimeObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("ObservationDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Source", "ObservationDate");

                    b.ToTable("RawRegimeObservations");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawSectorObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectorValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SicCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Source", "FetchedAt");

                    b.ToTable("RawSectorObservations");
                });

            modelBuilder.Entity("Drps.Shared.Models.SourceStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<string>("FieldOrBarType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastFailureAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchedObservationCount")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("TrustState")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Source", "FieldOrBarType");

                    b.ToTable("SourceStatuses");
                });

            modelBuilder.Entity("Drps.Shared.Models.UniverseSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate", "Ticker")
                        .IsUnique();

                    b.ToTable("UniverseSnapshots");
                });

            modelBuilder.Entity("Drps.Shared.Models.UniverseSnapshotCoverage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("SourcesSucceeded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique();

                    b.ToTable("UniverseSnapshotCoverages");
                });

            modelBuilder.Entity("Drps.Shared.Models.WeeklyVarianceAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AbsoluteVariance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AlpacaValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("BarDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PercentVariance")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("TiingoValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Field", "WeekEndingDate");

                    b.ToTable("WeeklyVarianceAuditEntries");
                });

            modelBuilder.Entity("Drps.Shared.Models.WorkerRunRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllSourcesSucceeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("WorkerName", "RunDate");

                    b.ToTable("WorkerRunRecords");
                });

            modelBuilder.Entity("Drps.Shared.Models.AdjusterAllocation", b =>
                {
                    b.HasOne("Drps.Shared.Models.GateScore", null)
                        .WithMany()
                        .HasForeignKey("GateScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Drps.Shared.Models.GateScore", b =>
                {
                    b.HasOne("Drps.Shared.Models.GateParameters", null)
                        .WithMany()
                        .HasForeignKey("GateParameterVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Drps.Shared.Models.Position", b =>
                {
                    b.HasOne("Drps.Shared.Models.AdjusterAllocation", null)
                        .WithMany()
                        .HasForeignKey("AdjusterAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Drps.Shared.Models.GateScore", null)
                        .WithMany()
                        .HasForeignKey("GateScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Drps.Shared.Models.PositionReconciliationDiscrepancy", b =>
                {
                    b.HasOne("Drps.Shared.Models.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
