// <auto-generated />
using System;
using Drps.Calculator.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drps.Calculator.Persistence.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    [Migration("20260714141852_AddRvolIndicators")]
    partial class AddRvolIndicators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drps.Shared.Models.BarVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ComputationVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchedSourceCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrimarySourceValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SourceCount")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ToleranceApplied")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp", "Resolution");

                    b.ToTable("BarVerifications", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Drps.Shared.Models.DmaIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BarDate")
                        .HasColumnType("date");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HasExDividendEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Window")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "BarDate", "Window", "CalculationVersion")
                        .IsUnique();

                    b.ToTable("DmaIndicators");
                });

            modelBuilder.Entity("Drps.Shared.Models.RawExDividendObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ExDividendDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("VariancePct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "ExDividendDate");

                    b.ToTable("RawExDividendObservations", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Drps.Shared.Models.RawOhlcvBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp", "Resolution");

                    b.ToTable("RawOhlcvBars", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Drps.Shared.Models.RsiIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BarDate")
                        .HasColumnType("date");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HasExDividendEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "BarDate", "Period", "CalculationVersion")
                        .IsUnique();

                    b.ToTable("RsiIndicators");
                });

            modelBuilder.Entity("Drps.Shared.Models.RvolIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BarDate")
                        .HasColumnType("date");

                    b.Property<int>("BaselineWindow")
                        .HasColumnType("int");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HasExDividendEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "BarDate", "BaselineWindow", "CalculationVersion")
                        .IsUnique();

                    b.ToTable("RvolIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
